
default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: fl_database_development

test:
  <<: *default
  database: fl_database_test
  pool: 5
  timeout: 5000

production:
  <<: *default
  database: fl_database_production
  pool: 5
  timeout: 5000